# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_pb2 as image__pb2


class ImageProcessStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetHeightAndWidth = channel.unary_unary(
        '/ImageProcess/GetHeightAndWidth',
        request_serializer=image__pb2.ImageMsg.SerializeToString,
        response_deserializer=image__pb2.OutParams.FromString,
        )


class ImageProcessServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetHeightAndWidth(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageProcessServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetHeightAndWidth': grpc.unary_unary_rpc_method_handler(
          servicer.GetHeightAndWidth,
          request_deserializer=image__pb2.ImageMsg.FromString,
          response_serializer=image__pb2.OutParams.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageProcess', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
