# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import add_pb2 as add__pb2


class AddStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sum = channel.unary_unary(
        '/Add/Sum',
        request_serializer=add__pb2.Args.SerializeToString,
        response_deserializer=add__pb2.Output.FromString,
        )


class AddServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Sum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sum': grpc.unary_unary_rpc_method_handler(
          servicer.Sum,
          request_deserializer=add__pb2.Args.FromString,
          response_serializer=add__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Add', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
